apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: web-app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: web-app

  minReplicas: 2 # ночью минимум, но не 1
  maxReplicas: 5 # 4 пода справляются, ставим 5 на случай всплесков

  metrics:
  - type: Resource
    resource:
      name: cpu # память всегда одинаково расходуется, поэтому при скейлинге опираемся на cpu
      target:
        type: Utilization
        averageUtilization: 70

  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300